# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: custom
  custom_color:
    primary: "#007bff"
    secondary: "#6c757d"
    success: "#28a745"
    info: "#17a2b8"
    warning: "#ffc107"
    danger: "#dc3545"
    light: "#f8f9fa"
    dark: "#343a40"

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: "The highly-customizable Hugo Academic theme powered by Hugo Blox Builder. Easily create your personal academic website."
    twitter: "GetResearchDev"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    plausible: ""
    fathom: ""
    pirsch: ""
  verification:
    google: ""
    baidu: ""

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "BEM ITESA"
      image: "assets/media/logo.png"

# Site footer
footer:
  copyright:
    notice: "© {2025} Badan Eksekutif Mahasiswa ITESA. This work is licensed under {license}."
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
